### ISSUE TITLE
Looking for sample project with a working example

### ISSUE THREAD

**Issue by massfords** [furstenheim/step-functions-tester#1]
This looks really promising. Do you have a sample project that shows this working in a run state? I get the concept of starting the local step function jar and stubbing the lambdas but I'm getting errors at startup and wondering if it's due to a missing config.

Thanks in advance.

**Comment by furstenheim** [comment]
Hi @massfords, docker compose and sam compatibilty are really tricky and change a lot, even in minor versions. Make sure that you are running sam version 1.12 and docker-compose version 1.25.4.

I have it pending to change the code to increase the versions to newer ones, but it requires a lot of changes on the infra code.

As for a running project, you can check the tests of the actual package https://github.com/furstenheim/step-functions-tester/blob/master/test/test-runner.test.js

**Comment by furstenheim** [comment]
Hi, @massfords, I've updated the different versions (sam, docker-compose, docker image...) and specially fixed the docker version of the step functions image, which could be a problem you were facing, in case it was fetching the last version which was incompatible.

You can give it a try now, but really ensure that you are using exactly the versions described in the README for sam and docker-compose, since connectivity between sam and docker is very tricky and changes in patch versions.

BTW, one problem that you might be getting, most probably the project does not work on MacOS. I would gladly accept a PR with a fix for that, Linux and Mac have a lot of differences in networking when connecting to docker and there are a lot of incompatibilities.

I've also uploaded an example to a single repo https://github.com/furstenheim/step-function-tester-example. But it is pretty much one test of the repo itself. Only difference is that the library is installed through NPM instead of accessing it locally.

**Comment by massfords** [comment]
@furstenheim thanks for following up on this. I'm on macOS so I expect that's still a blocker. It was still really helpful reviewing the code and your approach.
